### PR TITLE
Architecture review discussion for SAP on Azure

### PR DESCRIPTION
**Pull request by Anbanerj**
Architecture review discussion for SAP on Azure.

### CODE REVIEW

**Comment by chrisreddington** [comment]
Hey @Anbanerj , I think this is a good step.

Some thoughts 
-  Could you consider expanding the Purpose lines in "SAP Landscape Design". What is the purpose of understanding the driving factors / how could these impact/influence the architecture?
- Could you include extra links where appropriate? As this is publicly available, could be useful to link to tools (such as the SAP Quicksizer report)
- Throughout the doc, could you take a look at the "Purpose" lines (i.e. those lines in non-bold text that follow a question)? These should explain why the question is being asked, and what points the customer / engineer / person reading the doc needs to consider. I feel this could be fleshed out, here are some specific examples that could benefit -
    - What are the availability SLAs. Can you explain the current High Availability design? - In the next line, rather than saying refer.... Could you explain why High Availability is important, especially for SAP (which is generally a business critical workload)
     - "Can you explain the process for the Failover in case of a Disaster and what is the frequency of disaster recovery testing?" - Why is this important? Why is identifying stakeholders important? What other dependencies may hang off this?
     - "What is the Data Archiving Strategy?" - What are the different options available from a Data Archiving perspective? What factors should the customer consider to come to a decision?
     - "Are you planning to change the operating system and database of the systems during migration to Azure?" - Please can you explain the difference between Homogenous / Heterogenous migration, to make it easier for the end-reader?
     - "Do you have the high level plan for migration and is the partner for the project delivery identified?" - We should have a purpose line here
     - "How do you monitor different layers of the systems?" - We should have a purpose line here too

Overall, looks like it's heading in the right direction and has some good questions in there to get the discussions going!

**Review by WillEastbury — CHANGES_REQUESTED** [review]
Hey Anjan, 

I'd like to see a little more information around this section …  

"SAP application servers and the Central Services clusters can scale up/down or scale out by adding more instances.
    The database VMs can scale up/down with limitations on maximum size(4TB) of the VM. " 


I'd also like to see some context on WHY the questions are important, I.e. What should you do with the answers to the questions that the customer and or partner gives you.

**Comment by WillEastbury** [comment]
Hey Anjan,

That's much better, there are still a few spelling errors in the document and this is a public repo - if we could run this page through a spell checker, then we should be good to go from there.

Thanks,
Will

**Comment by Anbanerj** [comment]
Thanks Will. I have corrected the spelling errors.

**Comment by WillEastbury** [comment]
That's much better - merging.

**Pull request merged**
