### PR TITLE
Reference the Microsoft Azure Well-Architected Framework

### PR DESCRIPTION
**Pull request by MikeBazMSFT**
This week, we introduced the Microsoft Azure Well-Architected Framework.  There's a lot of overlap there with what we have here, but ultimately as that is the public direction for architecture guidance, I feel we need to follow that lead.  Some of the content we were referencing before is subsumed into the new framework.

There is more work to do here, because the existence of the self-guided review I believe potentially impacts our approach to delivery overall, but I at least wanted to get something that shows we're keeping up here.

### CODE REVIEW

**Comment by MikeBazMSFT** [comment]
Are there changes needed on this?

**Comment by MikeBazMSFT** [comment]
@xstof is there a change needed here?  it's been months now.

**Comment by xstof** [comment]
Honestly; I have no idea why I'd be reviewer here as to my knowledge I don't own this content?  I kindly suggest you work with engineering enablement here.  My apologies.

**Comment by MikeBazMSFT** [comment]
@xstof you're listed at https://github.com/Azure/fta-architecturalreview/blob/4f2a8d18369af65d450c82ed7d7c8fbb7623e033/CODEOWNERS#L13 so you should get that resolved.  I'm sure that's why the system automatically tagged you as the reviewer.  @colincole you're listed as the other possible reviewer.

**Comment by arsenvlad** [comment]
Looks good to me. @matticusau could you please merge?

**Comment by Matticusau** [comment]
FYI
I believe the CODEOWNERS hasn't been updated since it originally was created but there has been changes in leads etc. I will update it to reflect the current category leads etc. They can then suggest additional changes as needed

**Pull request merged**
